### ISSUE TITLE
Kommentare sind leider nicht möglich

### ISSUE THREAD

**Issue by Debakana** [jayAitch256/Arduino-ToneMusic#1]
Aufgrund der derzeitigen Struktur der Bibliothek scheint es nicht möglich zu sein, in die Melodien Kommentare einzufügen. Dies wäre jedoch sehr praktisch um beispielsweise Takte zu markieren.

**Comment by Debakana** [comment]
![comment_not_possible](https://user-images.githubusercontent.com/71189467/93001957-4a7c0380-f533-11ea-9eeb-83c610ef5e48.JPG)

**Comment by jayAitch256** [comment]
Jep, das stimmt... liegt daran, dass das Ganze eigentlich nur ein großes eindimensionales Array ist, das zur besseren Übersicht mit Backslashes auf mehrere Zeilen aufgeteilt wird.

**Kommentieren ist trotzdem möglich, solange der Kommentar vor dem Backslash steht...** man muss also ein bisschen tricksen:

```
#define MELODY1 { \
VIERTEL, b3, NORMAL, /* Comment */ \ 
HALBE, a3, NORMAL \
}
```

ODER

```
#define MELODY1 { \
/* Comment */ VIERTEL, b3, NORMAL, \ 
HALBE, a3, NORMAL \
}
```

ODER

```
#define MELODY1 { \
VIERTEL, b3, NORMAL, \ 
/* Comment */  \
HALBE, a3, NORMAL \
}
```
